### PR TITLE
Add seeder file

### PR DESCRIPTION
**Pull request by zacjones91**
This PR is all about the database seeder - seeder.py creates enough data to get us started. Also contains django_data.sh, which is the the bash script to delete database, re-run migrations, and seed a new database.

### CODE REVIEW

**Comment by zacjones91** [comment]
To run the script, type: django_data.sh Bangazon1 seeder

**Comment by braddavistech** [comment]
👍 Awesome work my friend!!!

**Comment by Nolan-Little** [comment]
👍

**Comment by jasehackman** [comment]
👍

**Pull request merged**
